version: '3'

services:
  db:
    image: mysql:8
    ports:
      - "3305:3306"
    environment:
      - MYSQL_DATABASE='projDataBase'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='password'
      - MYSQL_ROOT_PASSWORD='password'

  web:
    build: .
    command: python manage.py runserver
    ports:
      - "8000:8000"
